lua/onedarkpro/colors/onedark.lua
lua/onedarkpro/colors/onelight.lua
lua/onedarkpro/theme.lua

Hi there! Thanks for the theme!
This PR allows syntax highlighting to be used in diffs, and sets some default diff background colors that go well with that change. The result is (intentionally) similar to GitHub's diff rendering.
Hope this is helpful!
Before:
After:
Instead of changing the theme's defaults, I imagine it would also be possible to allow the fg colors I removed to be disabled from the plugin's settings, so that users would have the option to use syntax highlighting if they wanted.
- Remove the fg color on diff lines so that normal syntax colors are used
- Use darker background colors for the diffs, so that the text (which is no longer dark) is still legible
- If there is already a way to override the fg colors set for diffs …

Enable syntax-highlighted diffs

---

lua/lualine/themes/onedarkpro.lua
lua/onedarkpro/themes/onedark.lua
lua/onedarkpro/themes/onedark_vivid.lua
lua/onedarkpro/themes/onelight.lua

The biggest change is that the default colors for the part of the lualine status line where the git info is displayed are better (IMO).
Additionally:
1. New configurable color to give greater control of the appearance of the lualine to users
2. Correctly dim the statusline bg in inactive windows to match the bg of the editor body
(This doesn't impact the light theme much.)
Before (onedark/vivid/light)
After

Improve lualine colors in inactive windows

---

README.md

I've gotten bit by this a few times: you make a change, you even regenerate the cache, and you can't get your change to work... because you forgot to reload your config (e.g., source it or restart neovim) before running the cache command. It's obvious once you realize it, but can be confusing before you get there.

Note that you must reload config and regenerate cache

---

lua/onedarkpro/main.lua

Small change to append to `winhighlight` when setting it for inactive windows instead of overwriting it.
This basically makes `window_unfocused_color = true` play nicer with other plugins (or user configs) that also set `winhighlight`. One example: diffview.nvim with enhanced highlights enabled. I believe I also ran into a problem with `window_unfocused_color = true` and noice.nvim, but I haven't confirmed that this change is enough to fix that issue, as I'm not generally using noice.
I _swear_ I tried this during the initial implementation and it didn't work. :dizzy_face:

Append to winhighlight instead of overwriting it

---

lua/onedarkpro/highlights/filetypes/rust.lua

In Rust, stuff like `const` gets highlighted as `@storageclass`, which looks almost the same color as some variables. Really, it's a keyword.

add highlight for `@storageclass.rust`

---

lua/onedarkpro/highlights/filetypes/markdown.lua

Support for this was recently added to Treesitter.
neovim
vscode

Match vscode markdown checkbox styling

---

lua/onedarkpro/highlights/filetypes/markdown.lua

https://github.com/olimorris/onedarkpro.nvim/pull/135 was broken. I added the `markdown_inline`s locally and it seemed to work, but alas it was just cached from a previous version without those.
This should be correct.

Fix markdown checkbox highlights

---

lua/onedarkpro/highlights/filetypes/php.lua

Example: `public` in `public function`
Before:
After:

PHP: Update highlights for type qualifiers

---

lua/onedarkpro/lib/hash.lua

- `{ string.byte }` is only faster if we re-use the table a lot
- The definition for `pairs` is `function pairs(t) return next, t, nil end` so we have another small optimization to use `next, t` instead of `pairs(t)` 
Benchmark was done on both `main` and `perf` branch
| branch | time (ms) |
| ------ | ---- |
| main | 0.554543993 |                                                                                  
| perf | 0.003715965 |
Benchmark code:
```lua
local O = require("onedarkpro.config").config
local hash = require "onedarkpro.lib.hash"
local iter = 1000
local start = vim.loop.hrtime()
for _ = 1, iter do
hash(O)
end
print((vim.loop.hrtime() - start) / iter / 1000000)
```
Ported from https://github.com/catppuccin/nvim/pull/410

feat(compile): remove table overhead for better performance

---

lua/onedarkpro/init.lua

With lazy.nvim each plugin's repo is in Detached HEAD which means there's no `.git/ORIG_HEAD`
Cache the `.git` folder modification date instead

fix(setup): ORIG_HEAD doesn't exist in Detached HEAD

---

after/queries/python/highlights.scm

In the task of tagging `@odp.constructor` onto various python built-in types, instead of querying "assignment right" (which handles only the specific case of assignment statements) we can query "call function." The latter takes care of all cases including built-in constructor calls in for_statements, while_statements, if_statements, argument lists, and even basic parenthesized expression.
Special case only:
```
(assignment right: (call (identifier) @odp.constructor)
(#any-of? @odp.constructor "range" "list" "tuple" "dict" "set" "frozenset" "str" "int" "float" "complex" "bytes" "bytearray" "memoryview")) 
```
Takes care of all cases:
```
(call function: (identifier) @odp.constructor
(#any-of? @odp.constructor "range" "list" "tuple" "dict" "set" "frozenset" "str" "int" "float" "complex" …
```

Updated after/queries/python/highlights.scm

---

lua/onedarkpro/highlights/filetypes/go.lua

Hello. Here is the PR according to [this](https://github.com/olimorris/onedarkpro.nvim/commit/434b67beced0b518804712ab04b8cf4bcf1aed7d#commitcomment-109954231). You can see screenshots below
This is how `go`  looks in VsCode
This is how `go` looks before this commit in neovim
And this is how `go` looks after this commit in neovim

feat: 'go' support improved

---

after/queries/python/highlights.scm

Achieves the same effect as the previous approach, but prevents the punctuation mark `.`  in `import` statements from being assigned the `@odp.import_module` group.
The original approach:
https://github.com/olimorris/onedarkpro.nvim/assets/69449791/a56fc7ba-bca7-47d6-906c-744fbc69216d
With this pull request:
https://github.com/olimorris/onedarkpro.nvim/assets/69449791/c12d6869-87d5-446f-9014-89261d5ee1bc

chore: Update python highlights.scm

---

after/queries/go/highlights.scm

**The Problem:**
With the defaults, the use of `gopls`'s semantic tokens and treesitter tokens inevitably leads to inconsistent syntax highlighting 
**The Cause:**
For such import statements, `gopls` only assigns semantic tokens to the package name (the last component of the import path) instead of the entire import path.
This inevitably leads to inconsistent highlighting if the user sets different colors for `@string.go` and `@lsp.type.namespace.go`
**The Solution:**
What this PR does is that it uses treesitter's after queries to capture the entire import path (not just the package name). This allows the theme to treat the entire import path as a single entity under the `@odp.import_module` highlight group. That way, it is possible for users to create consistent highlighting for Go …

feat: Add after queries for Go to ensure consistent syntax highlighting

---

lua/onedarkpro/config.lua
lua/onedarkpro/highlights/plugins/rainbow_delimiters.lua

[HiPnish/nvim_ts_rainbow2](https://github.com/HiPhish/nvim-ts-rainbow2) deprecated and migrate to [HiPnish/rainbow-delimiters.nvim](https://github.com/HiPhish/rainbow-delimiters.nvim)
Preview:

feat(plugin): support rainbow_delimiters

---

README.md
lua/lualine/themes/onedark.lua
lua/lualine/themes/onedark_dark.lua
lua/lualine/themes/onedark_vivid.lua
lua/lualine/themes/onelight.lua
lua/onedarkpro/config.lua

Adding transparency option to Lualine

---

README.md
examples/c.c
lua/onedarkpro/config.lua
lua/onedarkpro/highlights/filetypes/c.lua

The theme was missing quite a few things to make it match VSCode.
VSCode:
Neovim:
I can't do anything about the `LOG` line just yet. The tree-sitter grammar isn't detailed enough and clangd doesn't seems to provide good tokens here.

fix: Match C source highlighting to VSCode

---

lua/onedarkpro/extra/alacritty.lua

fix: convert alacritty template to valid toml

---

lua/onedarkpro/highlights/plugins/nvim_tree.lua

Hello, I noticed that in the original nvim tree there is a background highlight for the line that your cursor is on:
I've noticed it in other themes as well but it seems as though it isn't appearing in this theme currently, so I added it in using the `palette.grey` value, here is the before and after:
I used `palette.grey` to try and stick with convention, but if we want some other colour then I'm happy for that too
I was going to just add it for my own config, but since it appears to be the default for nvim-tree and a lot of the themes that interact with nvim-tree I thought I should submit a PR in case this is desirable as a default
Thanks!

Added background highlight to cursor for nvim tree

---

extras/ghostty/onedarkpro_onedark
extras/ghostty/onedarkpro_onedark_dark
extras/ghostty/onedarkpro_onedark_vivid
extras/ghostty/onedarkpro_onelight
lua/onedarkpro/extra/ghostty.lua
lua/onedarkpro/extra/init.lua

Adds support for [Ghostty](https://ghostty.org/) terminal.
Since Ghostty uses text-based configuration files with no extension, I also added support for this in `lua/onedarkpro/extra/init.lua` with usage denoted by `ft=""`.

feat(extras): Add Ghostty theme

---

lua/onedarkpro/highlights/plugins/snacks.lua

Added the rest of the palette for SnacksIndentScope{1-8}, allowing users to have rainbow scope highlighting!
[Kooha-2025-04-16-17-06-18.webm](https://github.com/user-attachments/assets/2b0fc77b-b1d6-4416-9c56-f721a8b88b6e)
Usage:
```lua
indent = {
scope = {
hl = {
"SnacksIndentScope1",
"SnacksIndentScope2",
"SnacksIndentScope3",
"SnacksIndentScope4",
"SnacksIndentScope5",
"SnacksIndentScope6",
"SnacksIndentScope7",
"SnacksIndentScope8",
}
}
}
```

feat(snacks.indent): Added extra highlights for SnacksIndentScope

---

after/queries/python/highlights.scm

Before this pr, the `@odp.import_module` capture missed the `import xxx as yyy` case.
Not sure why the `CalledProcessError` is part of `@odp.import_module` highlight though. Attached the info below
Inspect the highlight for `CalledProcessError`

feat(python): add highlight for aliased imports in highlights.scm
