olimorris/onedarkpro.nvim

lua/onedarkpro/config.lua, lua/onedarkpro/plugins/notify.lua
Add some highlight group for nvim-notify.
=> feat: :sparkles: add support for nvim-notify plugin

lua/onedarkpro/plugins/telescope.lua
https://user-images.githubusercontent.com/50273941/180245940-ae618794-4127-47c7-a2ff-e7ffd42cce27.mp4
https://user-images.githubusercontent.com/50273941/180245967-188a8bb7-dfa6-40a3-9871-ad8f1d9fa6b1.mp4
https://user-images.githubusercontent.com/50273941/180246010-7c0a730c-c959-4a61-8ca6-7192283ed1e2.mp4
https://user-images.githubusercontent.com/50273941/180246022-44594422-e442-4342-ab10-60ad09ec6558.mp4
=> fix telescope titles color

lua/onedarkpro/plugins/telescope.lua
Reverts olimorris/onedarkpro.nvim#62
=> Revert "fix telescope titles color"

lua/onedarkpro/init.lua
=> fix: don't overwrite upvalue `M.override`

README.md, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/plugins/op_nvim.lua
Fixes #84 
Adds a colorscheme plugin for `op.nvim`
=> Add op.nvim colorscheme

lua/onedarkpro/highlights/editor.lua, lua/onedarkpro/themes/onedark.lua, lua/onedarkpro/themes/onedark_dark.lua, lua/onedarkpro/themes/onedark_vivid.lua, lua/onedarkpro/themes/onelight.lua
=> Match backgrounds for float contents and borders

lua/onedarkpro/highlights/editor.lua, lua/onedarkpro/main.lua
=> Fix background color of folds in inactive windows

lua/onedarkpro/lib/color.lua
Okay, this one is just so I can get rid of some diagnostics in my editor. 😅
Before:
After (note `nil`):
=> Mark bg and fg as optional params in darken() and lighten()

README.md, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/plugins/leap.lua
=> add leap.nvim plugin

after/queries/typescript/highlights.scm, examples/typescript.ts, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/filetypes/typescript.lua, lua/onedarkpro/lib/compile.lua
Testing out custom Treesitter queries. Pretty proud of these queries...
=> feat: add custom typescript treesitter queries

README.md, doc/onedarkpro.nvim.txt, lua/onedarkpro/highlight.lua, lua/onedarkpro/highlights/editor.lua, lua/onedarkpro/highlights/filetypes/html.lua, lua/onedarkpro/highlights/filetypes/markdown.lua, lua/onedarkpro/highlights/plugins/indentline.lua, lua/onedarkpro/highlights/plugins/nvim_bqf.lua, lua/onedarkpro/highlights/plugins/nvim_lsp.lua, lua/onedarkpro/highlights/plugins/polygot.lua, lua/onedarkpro/highlights/plugins/treesitter.lua, lua/onedarkpro/highlights/syntax.lua, lua/onedarkpro/init.lua, lua/onedarkpro/lib/compile.lua, lua/onedarkpro/utils/init.lua, tests/config_spec.lua, tests/config_spec.vim
Improved custom highlights, preserving default configuration when modifying styles or colors
=> Improved custom highlights

lua/onedarkpro/extra/foot.lua, plugin/onedarkpro.vim
[foot](https://codeberg.org/dnkl/foot) is my choice of terminal emulator
=> added command to export foot color scheme

README.md, doc/onedarkpro.nvim.txt, lua/onedarkpro/extra/rio.lua, lua/onedarkpro/utils/template.lua, plugin/onedarkpro.vim
Add theme exporter for the terminal [Rio](https://github.com/raphamorim/rio).
=> feat: add rio terminal theme

README.md
Readme for #215 
Forgot it yesterday 😂
=> docs: plugin rainbow_delimiters readme #215

README.md, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/plugins/vim_dadbod_ui.lua
https://github.com/kristijanhusak/vim-dadbod-ui
=> feat: add vim-dadbod-ui plugin support

lua/onedarkpro/extra/alacritty.lua
=> fix(alacritty): update file to compatible with 0.13

README.md, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/plugins/blink_cmp.lua
Add support for [blink.cmp](https://github.com/saghen/blink.cmp).
Before:
After:
=> add blink_cmp support

README.md, doc/onedarkpro.nvim.txt, lua/onedarkpro/config.lua, lua/onedarkpro/highlights/plugins/gitgraph_nvim.lua
Add `gitgraph.nvim` https://github.com/isakbm/gitgraph.nvim
=> feat(plugins): gitgraph.nvim

README.md, extras/tmux/onedarkpro_onedark.tmux, extras/tmux/onedarkpro_onedark_dark.tmux, extras/tmux/onedarkpro_onedark_vivid.tmux, extras/tmux/onedarkpro_onelight.tmux, lua/onedarkpro/extra/init.lua, lua/onedarkpro/extra/tmux.lua
Added a tmux theme using [TokyoNight's](https://github.com/folke/tokyonight.nvim) tmux theme as the base (All credits go to him!). I've also added acknowledgement for it in the README. Let me know if everything seems good!
OneDark:
OneDark Dark:
OneDark Vivid:
OneLight:
=> feat(extras): add tmux theme

lua/onedarkpro/lib/compile.lua, tests/config_spec.lua
=> fix: respect vim.o.background

after/queries/python/highlights.scm, lua/onedarkpro/highlights/filetypes/python.lua
=> feat(python): improve ts queries
